import fs from "node:fs/promises";
import path from "node:path";

/**
 * Project information for initialization
 */
export interface ProjectInfo {
  name: string;
  description: string;
  language: string;
  framework?: string;
}

/**
 * Create the project directory structure
 */
export async function createProjectStructure(
  projectPath: string,
  info: ProjectInfo,
): Promise<void> {
  const cocoPath = path.join(projectPath, ".coco");

  // Create directory structure
  const directories = [
    cocoPath,
    path.join(cocoPath, "state"),
    path.join(cocoPath, "checkpoints"),
    path.join(cocoPath, "logs"),
    path.join(cocoPath, "discovery"),
    path.join(cocoPath, "spec"),
    path.join(cocoPath, "architecture"),
    path.join(cocoPath, "architecture", "adrs"),
    path.join(cocoPath, "architecture", "diagrams"),
    path.join(cocoPath, "planning"),
    path.join(cocoPath, "planning", "epics"),
    path.join(cocoPath, "execution"),
    path.join(cocoPath, "versions"),
    path.join(cocoPath, "reviews"),
    path.join(cocoPath, "delivery"),
  ];

  for (const dir of directories) {
    await fs.mkdir(dir, { recursive: true });
  }

  // Create initial files
  await createInitialConfig(cocoPath, info);
  await createProjectState(cocoPath, info);
  await createGitignore(cocoPath);
  await createReadme(cocoPath, info);
}

/**
 * Create initial configuration file
 */
async function createInitialConfig(cocoPath: string, info: ProjectInfo): Promise<void> {
  const config = {
    project: {
      name: info.name,
      version: "0.1.0",
      description: info.description,
    },
    stack: {
      language: info.language,
      framework: info.framework,
    },
    provider: {
      type: "anthropic",
      model: "claude-sonnet-4-20250514",
    },
    quality: {
      minScore: 85,
      minCoverage: 80,
      maxIterations: 10,
      convergenceThreshold: 2,
    },
    persistence: {
      checkpointInterval: 300000,
      maxCheckpoints: 50,
    },
  };

  await fs.writeFile(path.join(cocoPath, "config.json"), JSON.stringify(config, null, 2), "utf-8");
}

/**
 * Create initial project state
 */
async function createProjectState(cocoPath: string, info: ProjectInfo): Promise<void> {
  const state = {
    id: `proj_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 9)}`,
    name: info.name,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    currentPhase: "idle",
    phaseHistory: [],
    currentTask: null,
    completedTasks: [],
    pendingTasks: [],
    lastScores: null,
    qualityHistory: [],
    lastCheckpoint: null,
  };

  await fs.writeFile(
    path.join(cocoPath, "state", "project.json"),
    JSON.stringify(state, null, 2),
    "utf-8",
  );
}

/**
 * Create .gitignore for coco directory
 */
async function createGitignore(cocoPath: string): Promise<void> {
  const content = `# Corbat-Coco

# Sensitive data
config.json

# Logs
logs/

# Checkpoints (can be large)
checkpoints/

# Session state
state/session.json
state/lock.json
`;

  await fs.writeFile(path.join(cocoPath, ".gitignore"), content, "utf-8");
}

/**
 * Create README for coco directory
 */
async function createReadme(cocoPath: string, info: ProjectInfo): Promise<void> {
  const content = `# Corbat-Coco Project: ${info.name}

This directory contains the Corbat-Coco project metadata and state.

## Structure

\`\`\`
.coco/
├── config.json           # Project configuration
├── state/                # Current project state
│   ├── project.json      # Main state file
│   └── session.json      # Active session
├── checkpoints/          # Recovery checkpoints
├── logs/                 # Execution logs
├── discovery/            # Discovery phase artifacts
├── spec/                 # Specification documents
├── architecture/         # Architecture documents
│   ├── adrs/             # Architecture Decision Records
│   └── diagrams/         # System diagrams
├── planning/             # Planning phase artifacts
│   └── epics/            # Epic definitions
├── execution/            # Execution tracking
├── versions/             # Task version history
├── reviews/              # Review documents
└── delivery/             # Deployment artifacts
\`\`\`

## Commands

- \`coco status\` - Show current progress
- \`coco resume\` - Resume from last checkpoint
- \`coco plan\` - Run/update planning
- \`coco build\` - Execute tasks

## Configuration

Edit \`config.json\` to customize:
- LLM provider and model
- Quality thresholds
- Checkpoint settings

---
Generated by Corbat-Coco v0.1.0
`;

  await fs.writeFile(path.join(cocoPath, "README.md"), content, "utf-8");
}
