/**
 * Documentation Generator for the OUTPUT phase
 *
 * Generates README, CONTRIBUTING, and other documentation
 */

import type { ProjectMetadata, DocumentationSet } from "./types.js";

/**
 * Documentation Generator
 */
export class DocsGenerator {
  private metadata: ProjectMetadata;

  constructor(metadata: ProjectMetadata) {
    this.metadata = metadata;
  }

  /**
   * Generate all documentation
   */
  generate(): DocumentationSet {
    return {
      readme: this.generateReadme(),
      contributing: this.generateContributing(),
      changelog: this.generateChangelog(),
      api: this.generateApiDocs(),
      deployment: this.generateDeploymentDocs(),
      development: this.generateDevelopmentDocs(),
    };
  }

  /**
   * Generate README.md
   */
  generateReadme(): string {
    const { name, description, packageManager } = this.metadata;
    const pm = packageManager || "npm";
    const installCmd = pm === "pnpm" ? "pnpm add" : "npm install";
    const runCmd = pm === "pnpm" ? "pnpm" : "npm run";

    return `# ${name}

${description}

[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
[![Node.js Version](https://img.shields.io/badge/node-%3E%3D22.0.0-brightgreen)](https://nodejs.org)

## Installation

\`\`\`bash
${installCmd} ${name}
\`\`\`

## Quick Start

\`\`\`bash
# Install dependencies
${pm} install

# Run in development
${runCmd} dev

# Build for production
${runCmd} build

# Run tests
${runCmd} test
\`\`\`

## Usage

\`\`\`typescript
import { ... } from '${name}';

// Your code here
\`\`\`

## Documentation

- [API Reference](./docs/api.md)
- [Contributing Guide](./CONTRIBUTING.md)
- [Changelog](./CHANGELOG.md)

## Development

\`\`\`bash
# Install dependencies
${pm} install

# Run tests
${runCmd} test

# Run tests with coverage
${runCmd} test:coverage

# Lint code
${runCmd} lint

# Format code
${runCmd} format
\`\`\`

## Contributing

Contributions are welcome! Please read the [Contributing Guide](./CONTRIBUTING.md) first.

## License

MIT License - see [LICENSE](./LICENSE) for details.

---

Generated by [Corbat-Coco](https://github.com/corbat-tech/corbat-coco)
`;
  }

  /**
   * Generate CONTRIBUTING.md
   */
  generateContributing(): string {
    const { name, packageManager } = this.metadata;
    const pm = packageManager || "npm";
    const runCmd = pm === "pnpm" ? "pnpm" : "npm run";

    return `# Contributing to ${name}

Thank you for your interest in contributing! This guide will help you get started.

## Development Setup

1. Fork and clone the repository
2. Install dependencies:
   \`\`\`bash
   ${pm} install
   \`\`\`
3. Create a new branch for your feature:
   \`\`\`bash
   git checkout -b feature/my-feature
   \`\`\`

## Development Workflow

### Running Tests

\`\`\`bash
# Run all tests
${runCmd} test

# Run tests in watch mode
${runCmd} test:watch

# Run tests with coverage
${runCmd} test:coverage
\`\`\`

### Linting and Formatting

\`\`\`bash
# Lint code
${runCmd} lint

# Format code
${runCmd} format
\`\`\`

### Building

\`\`\`bash
# Build for production
${runCmd} build

# Build in watch mode
${runCmd} dev
\`\`\`

## Commit Guidelines

We follow [Conventional Commits](https://www.conventionalcommits.org/):

- \`feat:\` New features
- \`fix:\` Bug fixes
- \`docs:\` Documentation changes
- \`style:\` Code style changes (formatting, etc.)
- \`refactor:\` Code refactoring
- \`test:\` Test additions or changes
- \`chore:\` Maintenance tasks

Example:
\`\`\`
feat: add user authentication

- Add login endpoint
- Add JWT token generation
- Add session management
\`\`\`

## Pull Request Process

1. Update documentation if needed
2. Add tests for new features
3. Ensure all tests pass
4. Update the CHANGELOG.md
5. Submit your pull request

### PR Checklist

- [ ] Tests added/updated
- [ ] Documentation updated
- [ ] CHANGELOG.md updated
- [ ] All tests passing
- [ ] Code formatted and linted

## Code Style

- Use TypeScript for all new code
- Follow existing code patterns
- Add JSDoc comments for public APIs
- Keep functions small and focused
- Write meaningful variable names

## Questions?

Feel free to open an issue if you have questions or need help!
`;
  }

  /**
   * Generate CHANGELOG.md
   */
  generateChangelog(): string {
    const { name, version } = this.metadata;
    const date = new Date().toISOString().split("T")[0];

    return `# Changelog

All notable changes to ${name} will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [${version}] - ${date}

### Added
- Initial release
- Core functionality

### Changed
- N/A

### Deprecated
- N/A

### Removed
- N/A

### Fixed
- N/A

### Security
- N/A

---

## Release Notes Format

### Added
For new features.

### Changed
For changes in existing functionality.

### Deprecated
For soon-to-be removed features.

### Removed
For now removed features.

### Fixed
For any bug fixes.

### Security
For vulnerabilities.
`;
  }

  /**
   * Generate API documentation
   */
  generateApiDocs(): string {
    const { name } = this.metadata;

    return `# API Reference

## ${name}

This document provides the API reference for ${name}.

## Table of Contents

1. [Installation](#installation)
2. [Configuration](#configuration)
3. [API](#api)
4. [Examples](#examples)

## Installation

\`\`\`bash
npm install ${name}
\`\`\`

## Configuration

Configuration options:

| Option | Type | Default | Description |
|--------|------|---------|-------------|
| ... | ... | ... | ... |

## API

### Functions

#### \`functionName(params)\`

Description of the function.

**Parameters:**
- \`param1\` (Type): Description

**Returns:**
- Type: Description

**Example:**
\`\`\`typescript
const result = functionName(param1);
\`\`\`

## Examples

### Basic Usage

\`\`\`typescript
import { ... } from '${name}';

// Example code
\`\`\`

### Advanced Usage

\`\`\`typescript
// Advanced example
\`\`\`
`;
  }

  /**
   * Generate deployment documentation
   */
  generateDeploymentDocs(): string {
    const { name } = this.metadata;

    return `# Deployment Guide

## ${name}

This guide covers deploying ${name} to various environments.

## Prerequisites

- Node.js 22+
- Docker (optional)
- Cloud provider account (for cloud deployment)

## Environment Variables

| Variable | Required | Default | Description |
|----------|----------|---------|-------------|
| NODE_ENV | No | development | Environment mode |
| PORT | No | 3000 | Server port |

## Deployment Options

### 1. Docker Deployment

\`\`\`bash
# Build the image
docker build -t ${name} .

# Run the container
docker run -p 3000:3000 ${name}
\`\`\`

### 2. Docker Compose

\`\`\`bash
docker compose up -d
\`\`\`

### 3. Cloud Platforms

#### AWS (ECS/Fargate)

1. Push image to ECR
2. Create ECS task definition
3. Create ECS service

#### Google Cloud (Cloud Run)

\`\`\`bash
gcloud run deploy ${name} --source .
\`\`\`

#### Azure (Container Apps)

\`\`\`bash
az containerapp up --name ${name} --source .
\`\`\`

## Health Checks

The application exposes health endpoints:

- \`GET /health\` - Basic health check
- \`GET /ready\` - Readiness check

## Monitoring

Configure monitoring with your preferred provider:

- Prometheus metrics (optional)
- Structured logging (JSON)
- Error tracking (Sentry, etc.)

## Scaling

Horizontal scaling recommendations:

- CPU-based: 70% threshold
- Memory: 80% threshold
- Request latency: p99 < 500ms
`;
  }

  /**
   * Generate development documentation
   */
  generateDevelopmentDocs(): string {
    const { packageManager } = this.metadata;
    const pm = packageManager || "npm";
    const runCmd = pm === "pnpm" ? "pnpm" : "npm run";

    return `# Development Guide

## Getting Started

### Prerequisites

- Node.js 22+
- ${pm}

### Setup

\`\`\`bash
# Clone the repository
git clone <repository-url>
cd <project-directory>

# Install dependencies
${pm} install

# Start development server
${runCmd} dev
\`\`\`

## Project Structure

\`\`\`
├── src/              # Source code
│   ├── index.ts      # Entry point
│   └── ...
├── tests/            # Test files
├── docs/             # Documentation
├── dist/             # Build output
├── package.json      # Dependencies
└── tsconfig.json     # TypeScript config
\`\`\`

## Development Commands

| Command | Description |
|---------|-------------|
| \`${runCmd} dev\` | Start development server |
| \`${runCmd} build\` | Build for production |
| \`${runCmd} test\` | Run tests |
| \`${runCmd} test:watch\` | Run tests in watch mode |
| \`${runCmd} test:coverage\` | Run tests with coverage |
| \`${runCmd} lint\` | Lint code |
| \`${runCmd} format\` | Format code |

## Debugging

### VS Code

1. Open the project in VS Code
2. Press F5 or use the debug panel
3. Select "Debug Node.js" configuration

### Node Inspector

\`\`\`bash
node --inspect dist/index.js
\`\`\`

## Testing

### Running Tests

\`\`\`bash
# All tests
${runCmd} test

# Specific test file
${runCmd} test path/to/test.ts

# With coverage
${runCmd} test:coverage
\`\`\`

### Writing Tests

\`\`\`typescript
import { describe, it, expect } from 'vitest';

describe('MyFunction', () => {
  it('should work correctly', () => {
    expect(myFunction()).toBe(expected);
  });
});
\`\`\`

## Code Style

- TypeScript strict mode
- ESLint for linting
- Prettier for formatting

## Troubleshooting

### Common Issues

1. **Node version mismatch**
   - Use \`nvm use\` to switch to correct version

2. **Dependency issues**
   - Delete \`node_modules\` and reinstall

3. **Build errors**
   - Check TypeScript configuration
   - Ensure all types are correct
`;
  }
}

/**
 * Create a documentation generator
 */
export function createDocsGenerator(metadata: ProjectMetadata): DocsGenerator {
  return new DocsGenerator(metadata);
}
